In [1]:
import numpy as np
import torch

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [9]:
t3 = torch.tensor([[[11,12,13],[14,15,16]],[[14,15,16],[17,18,19.]]])
t3

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[14., 15., 16.],
         [17., 18., 19.]]])

In [22]:
t4 = torch.tensor([[11,12],[15,14],[16,17.]])
t4

tensor([[11., 12.],
        [15., 14.],
        [16., 17.]])

In [10]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [11]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [13]:
print(t3)
t3.shape

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[14., 15., 16.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

# Tensor Operations

In [14]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

In [15]:
y = x * w + b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
# calculo das derivadas
y.backward()

In [18]:
print('dy/dx',x.grad)
print('dy/dw',w.grad )
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


# Tensor Functions

In [19]:
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [23]:
t7 = torch.cat((t4,t6))
t7

tensor([[11., 12.],
        [15., 14.],
        [16., 17.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [24]:
t8 = torch.sin(t7)
t8

tensor([[-1.0000, -0.5366],
        [ 0.6503,  0.9906],
        [-0.2879, -0.9614],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [25]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-1.0000, -0.5366],
         [ 0.6503,  0.9906]],

        [[-0.2879, -0.9614],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# Operability with Numpy

In [26]:
import numpy as np

In [27]:
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [28]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [29]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [1]:
import jovian

<IPython.core.display.Javascript object>

In [ ]:
jovian.commit(project='01-pytorch-basics')